config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about", as:"about"
    resources :items, only: [:index, :show]
    get '/customers/my_page'=>'customers#show', as:'show'
    get '/customers/unsubscribe/:id'=>'customers#unsubscribe', as:'unsubscribe'
    patch '/customers/withdraw'=>'customers#withdraw', as:'withdraw'
    resources :customers, only: [:edit, :update]
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all', as:'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm'=>'orders#confirm', as:'confirm'
    get '/orders/complete'=>'orders#complete', as:'complete'
    resources :orders, only: [:new, :create, :index, :show]
  end
  
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, presence: true
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.page(params[:page]).per(10)
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end
  
  def update
    @customer=Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)  
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
<h2 class="mb-5"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
    <div class="row form-group">
        <label for="customer_id", class="col-md-3">会員ID</label>
        <div class="customer_id col-md-9"><%= @customer.id %></div>
    </div>
    <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch, local: true do |f| %>
        <div class="row form-group">
            <label for="customer_name", class="col-md-3">氏名</label>
            <div class="customer_name col-md-9">
               <%= f.text_field :last_name %>
               <%= f.text_field :first_name %>
            </div>
        </div>
        <div class="row form-group">
            <label for="customer_name_kana", class="col-md-3">フリガナ</label>
            <div class="customer_name_kana col-md-9">
               <%= f.text_field :last_name_kana %>
               <%= f.text_field :first_name_kana %>
            </div>
        </div>
        <div class="row form-group">
            <label for="customer_postal_code", class="col-md-3">郵便番号</label>
           <div class="customer_postal_code col-md-9"><%= f.text_field :postal_code %></div>
        </div>
        <div class="row form-group">
            <label for="customer_address", class="col-md-3">住所</label>
            <div class="customer_address col-md-9"><%= f.text_field :address, size: 60 %></div>
        </div>
        <div class="row form-group">
            <label for="customer_telephone_number", class="col-md-3">電話番号</label>
           <div class="customer_telephone_number col-md-9"><%= f.text_field :telephone_number %></div>
        </div>
        <div class="row form-group">
            <label for="customer_email", class="col-md-3">メールアドレス</label>
           <div class="customer_email col-md-9"><%= f.text_field :email, size: 30 %></div>
        </div>
        <div class="row form-group">
            <label for="item_stastus", class="col-md-3">販売ステータス</label>
            <div class="item_stastus col-md-9">
                <%= f.radio_button :is_deleted, "false" %>有効
                <%= f.radio_button :is_deleted, "true" %>退会
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-3"></div>
            <div class="col-md-9"><%= f.submit '変更を保存', class:'btn btn-success' %></div>
        </div>
    <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
<h2>会員一覧</h2>
    <div class="row">
        <table class="table">
            <thead class="table-active">
                <tr>
                    <th>会員ID</th>
                    <th>氏名</th>
                    <th>メールアドレス</th>
                    <th>ステータス</th>
                </tr>
            </thead>
            <tbody>
            <% @customers.each do |customer| %>
                <tr>
                    <td><%= customer.id %></td>
                    <td>
                        <%= link_to admin_customer_path(customer.id),style: "color: black;" do %>
                            <%= customer.last_name %><%= customer.first_name %>
                        <% end %>
                    </td>
                    <td><%= customer.email %></td>
                    <td>
                        <% if customer.is_deleted == false %>
                            <div class="text-success font-weight-bold"><%= "有効" %></div>
                        <% else %>
                            <div class="text-secondary font-weight-bold"><%= "退会" %></div>
                        <% end %>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
        <div class="mx-auto"><%= paginate @customers %></div>
    </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2 class="mb-5"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
  <table>
    <tr>
  	  <td class="p-2">会員ID</td>
  	  <td class="p-2"><%= @customer.id %></td>
    </tr>
    <tr>
  	  <td class="p-2">氏名</td>
  	  <td class="p-2">
  	      <%= @customer.last_name %>
  	      </%><%= @customer.first_name %>
      </td>
    </tr>
    <tr>
  	  <td class="p-2">フリガナ</td>
  	  <td class="p-2">
  	    <%= @customer.last_name_kana %>
  	    <%= @customer.first_name_kana %>
  	   </td>
    </tr>
    <tr>
  	  <td class="p-2">郵便番号</td>
  	  <td class="p-2"><%= @customer.postal_code %></td>
    </tr>
    <tr>
  	  <td class="p-2">住所</td>
  	  <td class="p-2"><%= @customer.address %></td>
    </tr>
    <tr>
  	  <td class="p-2">電話番号</td>
  	  <td class="p-2"><%= @customer.telephone_number %></td>
    </tr>
    <tr>
  	  <td class="p-2">メールアドレス</td>
  	  <td class="p-2"><%= @customer.email %></td>
    </tr>
    <tr>
  	  <td class="p-2", valign="top">会員ステータス</td>
  	  <td class="p-2">
          <% if @customer.is_deleted == false %>
              <div class="text-success font-weight-bold", valign="bottom"><%= "有効" %></div>
          　<% else %>
              <div class="text-secondary font-weight-bold"><%= "退会"  %></div>
          　<% end %>
  	  </td>
    </tr>
     <tr>
  	  <td class="p-2"></td>
  	  <td class="p-2">
          <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success btn-sm" %>
          <%= link_to "注文一覧を見る", admin_orders_path, class:"btn btn-info btn-sm ml-5" %>
  	  </td>
    </tr>
  </table>
</div>