config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about", as:"about"
    resources :items, only: [:index, :show]
    get '/customers/my_page'=>'customers#show', as:'show'
    get '/customers/unsubscribe/:id'=>'customers#unsubscribe', as:'unsubscribe'
    patch '/customers/withdraw'=>'customers#withdraw', as:'withdraw'
    resources :customers, only: [:edit, :update]
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all', as:'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm'=>'orders#confirm', as:'confirm'
    get '/orders/complete'=>'orders#complete', as:'complete'
    resources :orders, only: [:new, :create, :index, :show]
  end
  
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { 
        credit_card: 0, 
        transfer: 1 
    }
    
    enum status: { 
        waiting: 0, 
        paid_up: 1,
        working: 2,
        preparing: 3,
        shipped: 4
    }
    
    has_many :order_details, dependent: :destroy
    belongs_to :customer
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders=Order.page(params[:page]).per(10)
  end
  
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
  end
  
  def update
    @order=Order.find(params[:id])
    @order_details=@order.order_details
    @order.update(order_params)
    if @order.status=='paid_up' 
	     @order_details.update_all(making_status: 'waiting') 
    end
    redirect_to admin_order_path(@order.id)
  end
  
  private
  def order_params
      params.require(:order).permit(:postal_code, :address, :name, :payment_method, :total_payment, :status, :customer_id)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
    <h2>注文履歴一覧</h2>
    <div class="row">
        <table class="table">
            <thead class="table-active">
                <tr>
                    <th>購入日時</th></th>
                    <th>購入者</th>
                    <th>注文個数</th>
                    <th>注文ステータス</th>
                </tr>
            </thead>
            <tbody>
            <% @orders.each do |order| %>
                <tr>
                    <td>
                        <%= link_to admin_order_path(order.id),style: "color: black;" do %>
                            <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                        <% end %>
                    </td> 
                    <td><%= order.customer.last_name+order.customer.first_name %></td>
                    <td>
                        <% @total_amount = 0 %>
                        <% order.order_details.each do |order_detail| %>
                            <% @total_amount += order_detail.amount %>
                        <% end %>
                        <%= @total_amount %>
                    </td>
                    <td><%= order.status_i18n %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
        <div class="mx-auto"><%= paginate @orders %></div>
    </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
<h2>注文履歴詳細</h2>
    <div class="row">
        <div class="col">
            <table style="width:600px">
                <tr>
            	    <td class="font-weight-bold">購入者</td>
            	    <td>
                        <%= link_to admin_customer_path(@order.customer.id),style: "color: black;" do %>
                            <%= @order.customer.last_name %> <%= @order.customer.first_name %>
                        <% end %>
        	        </td>
                </tr>
                <tr>
            	    <td class="font-weight-bold">注文日</td>  
            	    <td>
            	        <%= @order.created_at.strftime('%Y/%m/%d') %>
                    </td>
                </tr>
                <tr>
            	    <td class="font-weight-bold">配送先</td>
            	    <td>
                	    〒<%= @order.postal_code %> <%= @order.address %>
            	    </td>
                </tr>
                <tr>
            	    <td></td>
            	    <td>
                	    <%= @order.name %>
            	    </td>
                </tr>
                <tr>
            	    <td class="font-weight-bold">支払方法</td>
            	    <td><%= @order.payment_method_i18n %></td>
                </tr>
                <tr>
            	    <td class="font-weight-bold">注文ステータス</td>
            	    <td>
            	        <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %> 
                          <%= f.select :status, [['入金待ち','waiting'], ['入金確認','paid_up'], ['製作中','working'], ['発送準備中','preparing'], ['発送済み','shipped']] %>
                          <%= f.submit '更新', class:'btn btn-sm btn-success' %>
                    　  <% end %>
            	    </td>
        	    </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-7 mt-4">
            <table class="table" style="width:auto">
                <thead class="table-active">
                    <tr>
                        <th style="width:25%">商品名</th>
                        <th style="width:20%">単価（税込）</th>
                        <th style="width:10%">数量</th>
                        <th style="width:15%">小計</th>
                        <th style="width:30%">製作ステータス</th>
                    </tr>
                </thead>
                <tbody>
                <% @order_details.each do |order_detail| %>
                    <tr>
                        <td><%= order_detail.item.name %></td> 
                        <td><%= order_detail.price.to_s(:delimited) %></td>
                        <td><%= order_detail.amount %></td>
                        <td><%= (order_detail.amount*order_detail.price).to_s(:delimited)  %></td>
                        <td>
                            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch, local: true do |f| %> 
                              <%= f.select :making_status, [['製作不可','unmanufacturable'], ['製作待ち','waiting'], ['製作中','working'], ['製作完了','completed']] %>
                              <%= f.submit '更新', class:'btn btn-sm btn-success' %>
                        　  <% end %>
                        </td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-5 d-flex align-items-end mb-4">
            <table class="ml-2" style="width:180px">
                <tbody>
                    <tr>
                        <td class="font-weight-bold" style="width:auto">商品合計</td>
                        <td style="width:auto"><%= (@order.total_payment-@order.shipping_cost).to_s(:delimited) %>円</td>
                    </tr>
                    <tr>
                        <td class="font-weight-bold" style="width:auto">送料</td>
                        <td style="width:auto"><%= @order.shipping_cost.to_s(:delimited) %>円</td>
                    </tr>
                    <tr>
                        <td class="font-weight-bold" style="width:auto%">請求金額合計</td>
                        <td style="width:auto"><%= @order.total_payment.to_s(:delimited) %>円</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>