config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: 'homes#top'
    get "/about"=>"homes#about", as:"about"
    resources :items, only: [:index, :show]
    get '/customers/my_page'=>'customers#show', as:'show'
    get '/customers/unsubscribe/:id'=>'customers#unsubscribe', as:'unsubscribe'
    patch '/customers/withdraw'=>'customers#withdraw', as:'withdraw'
    resources :customers, only: [:edit, :update]
    delete '/cart_items/destroy_all'=>'cart_items#destroy_all', as:'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm'=>'orders#confirm', as:'confirm'
    get '/orders/complete'=>'orders#complete', as:'complete'
    resources :orders, only: [:new, :create, :index, :show]
  end
  
  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
    
    def address_display
        '〒'+postal_code+'　'+address+'　'+name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    validates :amount, presence: true
    
    def subtotal
        item.with_tax_price*amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, presence: true
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :item_image
    
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre
    
    validates :genre_id, :name, :item_image, :introduction, :price, presence: true
    validates :is_active, inclusion: {in: [true, false]}
    
  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
    enum payment_method: { 
        credit_card: 0, 
        transfer: 1 
    }
    
    enum status: { 
        waiting: 0, 
        paid_up: 1,
        working: 2,
        preparing: 3,
        shipped: 4
    }
    
    has_many :order_details, dependent: :destroy
    belongs_to :customer
    
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    enum making_status: { 
        unmanufacturable: 0, 
        waiting: 1,
        working: 2,
        completed: 3
    }
    
    belongs_to :item
    belongs_to :order
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre=Genre.new
    @genres=Genre.all
  end
  
  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre=Genre.find(params[:id])
  end
  
  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
    
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item=Item.new
    @items=Item.page(params[:page]).per(10)
    @genre=@item.genre
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end
  
  def create
    @item=Item.new(item_params)
      if @item.save
        redirect_to admin_item_path(@item.id)
      else
        @items=Item.all
        redirect_to new_admin_item_path
      end
  end

  def show
    @item=Item.find(params[:id])
    @cart_item=CartItem.new
  end

  def edit
    @item=Item.find(params[:id])
    @genres=Genre.all
  end
  
  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  private
    def item_params
      params.require(:item).permit(:item_image, :name, :introduction, :genre_id, :price, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
     def after_sign_in_path_for(resource)
        case resource
        when Admin
            admin_orders_path
        when Customer
            root_path
        end
     end
    
    def after_sign_out_path_for(resource)
        case resource
        when :admin
            new_admin_session_path
        when :customer
            root_path
        end
    end
    
    protected

    def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <script src="https://kit.fontawesome.com/971aec3205.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!--link rel="stylesheet" href="app/assets/stylesheets/application.css"-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
      <header class="d-flex flex-wrap py-3 mb-4 border-bottom bg-light">
        <a class="navbar-brand ml-4" href="/"><%= image_tag 'nagano_cake.png', :size =>'100x70' %></a>
        <ul class="nav nav-pills ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item mr-5 mt-4">
                ようこそ、<%= current_customer.last_name %>さん！
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to show_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                マイページ
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to cart_items_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                カート
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to items_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                ログアウト
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item mr-4 mt-3">
              <%= link_to admin_items_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to admin_customers_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                会員一覧
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to admin_orders_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                注文履歴一覧
              <% end %>
            </li>
             <li class="nav-item  mr-4 mt-3">
              <%= link_to admin_genres_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                ジャンル一覧
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item mr-4 mt-3">
              <%= link_to about_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                About
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to items_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                商品一覧
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to new_customer_registration_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                会員登録
              <% end %>
            </li>
            <li class="nav-item mr-4 mt-3">
              <%= link_to new_customer_session_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' do %>
                ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </header>
    
    <%= yield %>
    
    <footer class="footer border-top fixed-bottom mt-5 p-3 bg-light">
      <div class="text-center text-dark mt-3">Nagano Cake</div>
    </footer>
    
  </body>
</html>